# Generated by Django 6.0.5 on 2026-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_service_image_url_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Digital Apex', max_length=150)),
                ('hero_title', models.CharField(blank=True, help_text='Primary hero headline for the website', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle displayed below the hero title', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Short description displayed on the contact or about sections')),
                ('email', models.EmailField(default='hello@digitalapex.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('location', models.CharField(default='New Delhi, India', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Info',
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('feedback', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='highlights',
            field=models.TextField(blank=True, help_text='Enter each highlight on a new line'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
